server:
  port: 3030

DB:
  path: 'mongodb://localhost/gwg-dev'

session:
  secret: 'guitar with guru is how you spell gwg'

facebook:
  clientID: 1409632195960125
  clientSecret: '5126a40dd1cb8f00f55e7434a3dfcbb2'
  host: 'http://guitarwith.guru'

google:
  clientID: '1008229016606-s7fjods4mi2h1me6bdh9mapv8154lmem.apps.googleusercontent.com'
  clientSecret: 'UrV8nwt9M9K9iyO5zqc6KYW7'
  host: 'http://guitarwith.guru'

redis:
  host: 'localhost'
  port: 6379

admin:
  emails: ['aakash.lpin@gmail.com', 'goyal64@gmail.com']

soundcloud:
  clientID: 'e63a38724fcd2b664ca141aeb20e6fd0'
  clientSecret: '06de11d34179c3375b1ec1a29e41e039'
  userAuth: 'https://soundcloud.com/connect'
  token: 'https://api.soundcloud.com/oauth2/token'