server:
  port: 3030

DB:
  USER: null
  PASSWORD: null
  NAME: 'gwg-dev'

session:
  secret: 'guitar with guru is how you spell gwg'

facebook:
  clientID: 424544477675893
  clientSecret: '1cdade0a6c1ec2038b04bb5606d4337d'
  host: 'http://localhost.com:3000'

redis:
  host: 'localhost'
  port: 6379