server:
  port: 3030

DB:
  USER: null
  PASSWORD: null
  NAME: 'gwg-dev'

session:
  secret: 'guitar with guru is how you spell gwg'

facebook:
  clientID: 1409632195960125
  clientSecret: '5126a40dd1cb8f00f55e7434a3dfcbb2'
  host: 'http://guitarwith.guru'

redis:
  host: 'localhost'
  port: 6379