server:
  port: 3030

DB:
  USER: null
  PASSWORD: null
  NAME: 'gwg'

rendrApp:

api:
  default:
    host: 'localhost.com:3030'
    protocol: 'http'

session:
  secret: this should be some long random string
