server:
  port: 3030

DB:
  USER: null
  PASSWORD: null
  NAME: 'gwg'

session:
  secret: 'guitar with guru is how you spell gwg'

facebook:
  clientID: 1409632195960125
  clientSecret: '92319b5f16b03c80cb8fbf1c9deb5a5f'

redis:
  host: 'localhost'
  port: 6379